### ISSUE TITLE
azurerm_key_vault_secret.example Issue

### ISSUE THREAD

**Issue by SachinHR** [piyushsachdeva/Terraform_AKS#2]
I followed the step which you mentioned in README file .... Everything is working fine except KV secret creation

│ Error: checking for presence of existing Secret "7XXXXXXXX6" (Key Vault "https://test-piyush-kv-1011.vault.azure.net/"): keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: appid=0XXXXXXXX6;oid=5XXXXXXXXa;iss=https://sts.windows.net/ee4XXXXXXXXd6/\r\nAction: 'Microsoft.KeyVault/vaults/secrets/getSecret/action'\r\nResource: '/subscriptions/dXXXXXXXX01/resourcegroups/test-piyush1-rg/providers/microsoft.keyvault/vaults/test-piyush-kv-1011/secrets/7cXXXXXXXX96'\r\nAssignment: (not found)\r\nDenyAssignmentId: null\r\nDecisionReason: 'DeniedWithNoValidRBAC' \r\nVault: test-piyush-kv-1011;location=canadacentral\r\n" InnerError={"code":"ForbiddenByRbac"}
│
│   with azurerm_key_vault_secret.example,
│   on main.tf line 46, in resource "azurerm_key_vault_secret" "example":
│   46: resource "azurerm_key_vault_secret" "example" {
│
╵
Releasing state lock. This may take a few moments...

**Comment by flavio-fernandes** [comment]
Having the same issue. Sad panda!!!

**Comment by piyushsachdeva** [comment]
I missed replying to this. You need to have Key vault admin role to be able to create secrets.
